<a href="https://colab.research.google.com/github/carolyneolive/curso_eng_dados/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **Trilhando Caminhos em Ciência de Dados**
1.1 Numpy


In [2]:
# Importando a biblioteca numpy
import numpy as np

In [3]:
# Criando um array de 1 dimensão

one_dim = np.array([0,1,2,3])

In [4]:
# Imprimindo o tipo de objeto
type(one_dim)

numpy.ndarray

In [5]:
# Imprimindo um array da lista
one_dim.ndim

1

In [7]:
# Criando um array de 2 dimensões
two_dim = np.array([(0,1,2,3),(4,5,6,7)])

In [9]:
# Imprimindo um array com as 2 dimensões
print(two_dim)

[[0 1 2 3]
 [4 5 6 7]]


In [10]:
# Cria um array aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((2,4))


array([[0.76686649, 0.71557757, 0.90149608, 0.20206   ],
       [0.01625254, 0.52038567, 0.4064319 , 0.75326584]])

In [11]:
# Cria um array com valotes esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5
# tipo um for em numpy
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
# Cria um array linear de 0 a 2 de máximo 9 elementos
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
# Cria um array de valores zero
# Cria um array com 3 linhas e 4 dimensões
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#**Diferenças entre Listas e Arrays**

# Listas

In [36]:
# Criando uma lista em Python
lista = [1,2,3]

In [37]:
# Imprimindo a lista
lista

[1, 2, 3]

In [38]:
# Multiplicar valores da lista por 2
# Obs: ele for uma variável do tipo lista ela não multiplica apenas duplica os valores
lista * 2

[1, 2, 3, 1, 2, 3]

In [28]:
# Calcular IMC de pessoas
pesos = [67,75,120,90]
altura = [1.68,1.54,1.75,1.32]

In [29]:
# Faz o calculo usando as listas
# Não é possivel fazer essa operação com lista, apenas com interiro. Como
# o Numpy é um biblioteca para operações matemática fica mais simples.
pesos / altura ** 2

In [39]:
# As lista aceita dados heterogêneos
lista = [1,3,'Casa', True]

In [40]:
# Duplicar a lista
lista * 2

[1, 3, 'Casa', True, 1, 3, 'Casa', True]

Operações matemáticas

In [42]:
# Criar um lista a partir de uma estrutura de repetição
lista = [i for i in range(10, 50,5)]
lista

[10, 15, 20, 25, 30, 35, 40, 45]

In [44]:
# Estrturura de repetiação a partir da lista
soma  = 0
for i in lista:
  soma+=i

print('Média:' + str(soma/len(lista)))

Média:27.5


Acessando elementos

In [48]:
# Acesso aos elementos da lista de acordo com sua posição
lista[1]


15

In [51]:
# Acessar todos elementos maior que 20, não é possível em uma lista visto que
#  ele não tem suporte para operacões lógicas
lista[lista>20]

#**Arrays**

In [20]:
# Transforme a variavel lista em um array Numpy
lista = np.array(lista)

In [21]:
# Imprimindo o tipo de objeto
type(lista)

numpy.ndarray

In [22]:
# Multiplicando cada elemento por 2
lista * 2

array([2, 4, 6])

In [23]:
# Transforme pesos = [67,75,120,90] e altura = [1.68,1.54,1.75,1.32] em array numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [24]:
  # Imprime o calculo de cada valor
  pesos /altura **2

array([23.73866213, 31.62421994, 39.18367347, 51.65289256])

In [32]:
# Criando Numpy com dados heterogêneos
a = np.array([1,3,'Casa', True])

In [34]:
# Numpy aceita apenas dados homogêneos para maniputação dos dados
# Não é possível visto que o Munpy faz operacões com cada um dos seus elementos
a * 2

In [35]:
# Repeti o valor do array 2 vezes
np.tile(a, 2)

array(['1', '3', 'Casa', 'True', '1', '3', 'Casa', 'True'], dtype='<U21')

Operações matemáticas


In [45]:
# Arange é o for do Numpy
n_array = np.arange(10, 50,5)

In [46]:
# Numpy já temos a função mean()
n_array.mean()

27.5

In [ ]:
# Acesso aos elementos no Numpy de acordo com sua posição
n_array[1]

In [52]:
# Acessar todos elementos maior que 20.
n_array[n_array>20]

array([25, 30, 35, 40, 45])

***Métodos e Atributos Úteis ***

In [ ]:
# Métodos disponíveis (digite o . pressione ctrl + enter )
# (todos os tipos de operações que posso usar neste array)
two_dim

In [60]:
# Retorna a forma do array no formato linhas e colunas
two_dim.shape

(2, 4)

In [61]:
# Retorna a quantidade de dimensões
two_dim.ndim

2

In [62]:
# Imprimindo o valor máximo do array
two_dim.max()

7

In [63]:
# Imprimindo o valor mínimo do array
two_dim.min()

0

In [64]:
# Imprimindo o valor méadia do array
two_dim.mean()

3.5

In [65]:
# Imprimindo o valor desvio padrão do array
two_dim.std()

2.29128784747792

In [66]:
# Identificar o tipo de elementos do array
two_dim.dtype

dtype('int64')

In [67]:
# Quantos elementos tenho dentro do array
two_dim.size

8

In [68]:
# Mostra a quantidade
two_dim.itemsize

8

In [69]:
# Somando todos os elementos do array
two_dim.sum()

28

**Transformando Array **

In [70]:
# Gera a transposta da Matriz (linha -> coluna)
two_dim.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [71]:
# Transforma em uma matriz de uma linha
# É muiti comum em bibliotecas como scikit-learn e keras
two_dim.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
# Criar um array aleatório
tree_dim = np.random.random((3,5))
tree_dim

array([[0.12269263, 0.94791947, 0.16092299, 0.75394438, 0.12585119],
       [0.53669484, 0.59622964, 0.98591211, 0.50504846, 0.2942555 ],
       [0.1490407 , 0.86611577, 0.63672925, 0.90024041, 0.61770629]])

In [76]:
# Transforma em uma matriz com 3 linhas e 4 colunas
tree_dim.reshape(5,3)

array([[0.12269263, 0.94791947, 0.16092299],
       [0.75394438, 0.12585119, 0.53669484],
       [0.59622964, 0.98591211, 0.50504846],
       [0.2942555 , 0.1490407 , 0.86611577],
       [0.63672925, 0.90024041, 0.61770629]])

In [79]:
# Adicionando elemento a um array
tree_dim = np.insert(tree_dim,2,1)
tree_dim

array([3.        , 3.        , 1.        , 0.12269263, 0.94791947,
       0.16092299, 0.75394438, 0.12585119, 0.53669484, 0.59622964,
       0.98591211, 0.50504846, 0.2942555 , 0.1490407 , 0.86611577,
       0.63672925, 0.90024041, 0.61770629])

In [ ]:
# Apagando o alemento da primeira posição do array
tree_dim = np.delete(tree_dim,[0])
tree_dim

In [83]:
# Gerando um arquivo . txt a partir de um array
np.savetxt("array.txt", tree_dim, delimiter=',')

**Funções que são úteis e pouco conhecidas**

In [89]:
# Repete o valor dos array lado a lado ordenado
x = np.array([1,2,3,4,5])
np.repeat(x,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [90]:
# Repete verticalmente três vezes
np.tile(x,(3,1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [91]:
# Inverte a ordem dos elementos do array
np.flip(x)

array([5, 4, 3, 2, 1])

In [92]:
# Produto acumulado de todos os elemntos anteriores no array
np.cumprod(x)

array([  1,   2,   6,  24, 120])

In [93]:
# Soma acumulada de todos os elementos anteriores no array
np.cumsum(x)

array([ 1,  3,  6, 10, 15])

In [94]:
# Diferença de todos os elementos anteriores no array
np.diff(x)

array([1, 1, 1, 1])

In [95]:
# Ordena os índices dos valores ordenados no arrays
# ele não print os elementos apenas os índeces
np.argsort(x)

array([0, 1, 2, 3, 4])

In [96]:
x = np.array([1,5,8,4])
np.argsort(x)

array([0, 3, 1, 2])

Acessando Dimensões no Array

In [98]:
# Gera um array aleatório de 10 linhas e 2 colunas formato linha,coluna
array_1 = np.random.random([10,2])

In [99]:
# Imprimindo o primeiro elemento (1 linha)
array_1[3]

array([0.09566156, 0.33655989])

In [103]:
# Imprimindo o primeiro elemento da coluna 0 [ 1 coluna]
array_1[0][0]



0.22580960993857258

In [102]:
# Segundo elemento da coluna escrito com vírgula, em que o primeiro valor
#específica a linha e o segundo o valor específico da coluna
array_1[1,0]

0.5788247796099218

In [104]:
# Imprimindo até 3 valores da voluna 1 - Chamamos de fatiamento (n-1 [índice 0, 1 e 2]])
array_1[:3,1]

array([0.15827633, 0.3466364 , 0.57870387])

In [105]:
# Imprimindo todos as linhas da coluna 1 multiplicada por 10
array_1[:,1]*10

array([1.58276328, 3.46636401, 5.78703866, 3.36559887, 3.01518102,
       7.0234284 , 6.09987925, 3.13745012, 6.35664648, 0.99786351])

In [106]:
# Criando um array multidimiensional de exemplo
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [110]:
# Fatiando o array em linhas
primeiras_linhas = array[:2]
ultima_linha = array[2:]

print("Primeiras linhas:")
print(primeiras_linhas)

print("\nÚltima linha:",ultima_linha)


Primeiras linhas:
[[1 2 3]
 [4 5 6]]

Última linha: [[7 8 9]]


In [112]:
# Fatiando o array em colunas
primeiras_colunas = array[:,:2]
ultima_coluna = array[:, 2:]

print("Primeiras colunas:")
print(primeiras_colunas)

print("\nÚltima coluna:")
print(ultima_coluna)

Primeiras colunas:
[[1 2]
 [4 5]
 [7 8]]

Última coluna:
[[3]
 [6]
 [9]]


In [118]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
# Imprimir de 1 a 5 pulando 2 números
# se fosse fazer na mão for i in range(1,len(n_array),2)
array[1:5:2]

array([[4, 5, 6]])

In [120]:
# Imprimindo os ímpares
array[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [121]:
# Imprimindo os pares
array[1::2]

array([[4, 5, 6]])

In [140]:
# Comparação retorna indíces
n_array > 30

array([False, False, False, False, False,  True,  True,  True])

In [139]:
# Se desejar ver os elementos
n_array[n_array > 30]

array([35, 40, 45])

In [142]:
# Soma os elementos de uma função
np.sum(array[array> 30])

45

In [144]:
# Substituição de valores < 20
array[array < 20] = 10
array

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [147]:
# Também podemos condicional com where
my_array = np.random.random([10,2])
print(my_array)
np.where(my_array < 0.30, 10, my_array)

[[0.27903536 0.72512008]
 [0.10832551 0.46852861]
 [0.10431445 0.88400701]
 [0.37489455 0.93628106]
 [0.40080669 0.00479245]
 [0.40747734 0.77553928]
 [0.11180528 0.6004191 ]
 [0.44144    0.53228469]
 [0.6845318  0.45491894]
 [0.43714723 0.35615551]]


array([[10.        ,  0.72512008],
       [10.        ,  0.46852861],
       [10.        ,  0.88400701],
       [ 0.37489455,  0.93628106],
       [ 0.40080669, 10.        ],
       [ 0.40747734,  0.77553928],
       [10.        ,  0.6004191 ],
       [ 0.44144   ,  0.53228469],
       [ 0.6845318 ,  0.45491894],
       [ 0.43714723,  0.35615551]])

In [151]:
# Somar as linhas, axis = 1
np.sum(my_array,axis = 1)


array([1.00415543, 0.57685413, 0.98832146, 1.31117561, 0.40559915,
       1.18301662, 0.71222438, 0.97372468, 1.13945074, 0.79330274])

In [152]:
# Somar as colunas, axis = 0
np.sum(my_array,axis = 0)

array([3.34977821, 5.73804672])

**Carregar Array Numpy a partir de arquivos de Texto**

In [157]:
# lendo um arquivo do tipo .txt
dataset = np.loadtxt('array.txt', delimiter=',')

In [158]:
dataset.shape

(17,)

In [159]:
dataset

array([3.        , 1.        , 0.12269263, 0.94791947, 0.16092299,
       0.75394438, 0.12585119, 0.53669484, 0.59622964, 0.98591211,
       0.50504846, 0.2942555 , 0.1490407 , 0.86611577, 0.63672925,
       0.90024041, 0.61770629])

In [165]:
# Carregando um arquivo dividido em 3 arrays
# utilize o ubpack para retornar o elemento transposto
a = np.loadtxt('array.txt', skiprows=1, unpack=True)


In [166]:
# Array a
a

array([1.        , 0.12269263, 0.94791947, 0.16092299, 0.75394438,
       0.12585119, 0.53669484, 0.59622964, 0.98591211, 0.50504846,
       0.2942555 , 0.1490407 , 0.86611577, 0.63672925, 0.90024041,
       0.61770629])

In [167]:
# Utilize genfromtxt para arquivos com valores faltantes
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos
# Utilize filling_values para substituir os valores faltantes ou em strings pelo valor especificado nesta variaável
dateset = np.genfromtxt('array.txt', skip_header=2, filling_values=0)

In [168]:
dateset

array([0.12269263, 0.94791947, 0.16092299, 0.75394438, 0.12585119,
       0.53669484, 0.59622964, 0.98591211, 0.50504846, 0.2942555 ,
       0.1490407 , 0.86611577, 0.63672925, 0.90024041, 0.61770629])

**Operações Matriciais **

In [ ]:
a = np.array([100, 200, 300])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

print(a[0],a[1],a[2])

In [173]:
# Subistituição de elementos
a[0] = 500
print(a)

[500 200 300]


#**Operações matriciais**

**Soma**

In [176]:
#1  2    5  6    6   8
#   +      =
#3  4     7  8   10 12

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x:" + str(x) + "\n")
print("y:" + str(y) + "\n")

# [[6.0  8.0]]
# [[10.0  12.0]]

# Para fazemos a soma da matriz podemos usar as formas
print(x + y)
print()
print(np.add(x,y))

x:[[1. 2.]
 [3. 4.]]

y:[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


Subitração

In [178]:
#1  2    5  6    6   8
#      -      =
#3  4     7  8   10 12

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x:" + str(x) + "\n")
print("y:" + str(y) + "\n")

# [[6.0  8.0]]
# [[10.0  12.0]]

# Para fazemos a subtração da matriz podemos usar as formas
print(x - y)
print()
print(np.subtract(x,y))

x:[[1. 2.]
 [3. 4.]]

y:[[5. 6.]
 [7. 8.]]

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


**Multiplicação**

In [179]:
#Multiplicação de elementos
#1  2    5  6    6   8
#      *      =
#3  4     7  8   10 12

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x:" + str(x) + "\n")
print("y:" + str(y) + "\n")

# [[6.0  8.0]]
# [[10.0  12.0]]

# Para fazemos a multiplicação da matriz podemos usar as formas
print(x * y)
print()
print(np.multiply(x,y))

x:[[1. 2.]
 [3. 4.]]

y:[[5. 6.]
 [7. 8.]]

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [180]:
#Multiplicação de matrizes
#1  2    5  6    1*5 + 2*7       1*5 + 2*8
#      *      =
#3  4     7  8   3*5 + 4*7       3*6 + 4*8

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x:" + str(x) + "\n")
print("y:" + str(y) + "\n")

# [[6.0  8.0]]
# [[10.0  12.0]]

# Multiplicação de matrizes
print(x.dot(y))
print()
print(np.dot(x,y))

x:[[1. 2.]
 [3. 4.]]

y:[[5. 6.]
 [7. 8.]]

[[19. 22.]
 [43. 50.]]

[[19. 22.]
 [43. 50.]]


**Divisão**

In [181]:
#Divisão de elementos
#[[ 0.2    0.3333]
#[ 0.4285  0.5  ]]

#1  2    5  6    0.2    0.3333
#      /      =
#3  4     7  8   0.4285  0.5

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x:" + str(x) + "\n")
print("y:" + str(y) + "\n")

# [[6.0  8.0]]
# [[10.0  12.0]]

# Para fazemos a multiplicação da matriz podemos usar as formas
print(x / y)
print()
print(np.divide(x,y))

x:[[1. 2.]
 [3. 4.]]

y:[[5. 6.]
 [7. 8.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Raiz quadrada

In [182]:
# Raiz quadrada os elementos de uma matriz
x = np.array([[1,2],[3,4]], dtype=np.float64)

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Construção de matrizes prontas

In [185]:
import numpy as np

a = np.zeros((2,2)) # array de zeros
print(a, '\n')

b = np.ones((1,2)) # array de uns
print(b, '\n')

c = np.full((2,2),7) # array de constatntes
print(c, '\n')

d = np.eye((2)) # matriz identidade
print(d, '\n')

e = np.random.random((2,2)) # array preenchida com valores rondomicos entre 0 e 1
print(e, '\n')

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[[0.95587652 0.84817367]
 [0.64552156 0.76819788]] 



In [186]:
# Acesso de elementos
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = a[:2, 1:3]
print(b, '\n')

[[2 3]
 [5 6]] 



In [187]:
array = np.arange(8)
print('Original array : \n', array)

# Shape array com 2 linhas e 2 colunas
array = np.arange(4).reshape(2,2)
print('\nArray resshape com 4 linhas e 2 colunas: \n', array)

# Shape array com 4 linhas e 2 colunas
array = np.arange(8).reshape(2,4)
print('\nArray resshape com 2 linhas e 4 colunas: \n', array)

# Array 3D
array = np.arange(8).reshape(2,2,2)
print('\nOriginal de array reshaped para 3D: \n', array)

Original array : 
 [0 1 2 3 4 5 6 7]

Array resshape com 4 linhas e 2 colunas: 
 [[0 1]
 [2 3]]

Array resshape com 2 linhas e 4 colunas: 
 [[0 1 2 3]
 [4 5 6 7]]

Original de array reshaped para 30: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [188]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # cria uma matriz vazia do mesmo shape que x

print(y)

# Adicionando um vetor v a cada linha da matriz x com o loop

for i in range(4):
  y[i,:] = x[i,:]+v

print(y)


[[101070510561414               0               0]
 [              0               0               0]
 [              0               0               0]
 [              0               0               0]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#Listas vs Arrays - Tempo de execução


In [58]:
import time
l1 = list(range(1000000))
l2 = np.arange(1000000)

# Usando list simples
start_time = time.time()
%time for i in range(len(l1)):l1[i]= l1[i]*2
end_time = time.time()
cpu_time = end_time - start_time

print('Tempo de CPU:', cpu_time, "segundos")

# Usando list comprehension
start_time = time.time()
%time l = [i*2 for i in l1]
end_time = time.time()
cpu_time = end_time - start_time

print('Tempo de CPU:', cpu_time, "segundos")

# Usando Numpy
start_time = time.time()
%time l2 = l2 *2
end_time = time.time()
cpu_time = end_time - start_time

print('Tempo de CPU:', cpu_time, "segundos")


CPU times: user 373 ms, sys: 2.02 ms, total: 375 ms
Wall time: 602 ms
Tempo de CPU: 0.6041648387908936 segundos
CPU times: user 96.5 ms, sys: 19.5 ms, total: 116 ms
Wall time: 118 ms
Tempo de CPU: 0.11972951889038086 segundos
CPU times: user 2.32 ms, sys: 1.06 ms, total: 3.38 ms
Wall time: 1.97 ms
Tempo de CPU: 0.0025925636291503906 segundos


#Exercício de Numpy

In [194]:
# Crie um array NumPy unidimensional com os números de 1 a 10.

x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [197]:
# Crie um array NumPy bidimensional 3x3 preenchido com zeros.
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [198]:
# Crie um array NumPy bidimensional 4x4 preenchido com uns.
x = np.ones((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [203]:
# Crie um array NumPy com 20 valores aleatórios entre 0 e 100.
# Função randint é específica para geração de números inteiros aleatórios.
x = np.random.randint(0,101,20)
print(x)

[82 53 15 14 50 61 78 26 96 40 94 35 28 88 25 45 77 73 37 26]


In [207]:
# Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.
x = np.arange(0,10, 0.5)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [209]:
# Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.
# Obs: Neste caso precisamos definir o tamanho
x = np.random.randint(1,101,size=(5, 5))
print(x)

[[82 89 97 16 60]
 [95 70 79 77 31]
 [59 51 98 72 37]
 [74 25 10 51 76]
 [93 19 80 57 69]]


In [218]:
# Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A = A[:,1]
print(A)

[2 5 8]


In [220]:
# Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.
x = np.array([1, 2, 3, 4, 5])
# Condição para encontrar os elementos pares
y = np.where(x % 2 == 0, -1, x)
print(y)


[ 1 -1  3 -1  5]


In [221]:
# Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.
x = np.array([1, 2, 3, 4, 5])
# Condição maior que dois
y = np.where(x > 2, 0, x)
print(y)

[1 2 0 0 0]


In [222]:
# Dado o array NumPy x = [1, 2, 3, 4, 5], normalize os valores do array de forma que a soma seja igual a 1.
x = np.array([1, 2, 3, 4, 5])
# Normalize os valores para que a soma seja igual a 1
y = x / np.sum(x)
print(y)

[0.06666667 0.13333333 0.2        0.26666667 0.33333333]


In [223]:
# Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


In [225]:
# Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.
x = np.array([1, 2, 3])
x = np.tile(x,3)
print(x)

[1 1 1 2 2 2 3 3 3]


In [228]:
# Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.
x = np.array([1, 2, 3])
# Concatenate é usada para concatenar dois ou mais arrays ao longo de um determinado eixo.
x = np.concatenate([x] * 3)
print(x)

[1 2 3 1 2 3 1 2 3]


In [229]:
# Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.
x = np.array([1, 2, 3])
x = np.repeat(x,3)
print(x)

[1 1 1 2 2 2 3 3 3]


In [232]:
# Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.
x = np.array([1, 2, 3])
x = x[::-1]
print(x)

[3 2 1]
